# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a69703f1801b80e2dcb8688539fa0bfebd26ea2678ac00c4ec029d8cf1e8799596ded476c4b3327a787357d1aa46665623f6058101c1f320a5636202d93d117

test:
  secret_key_base: 76d8015272c5276191f8bde2c29b8584ec071afe43adef196c768adac00ed8589c600e98a45b6434c2c7f460d40d18eda957fbec13580746c0da53126e90be94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
